using Azure;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using EventBooking.Core;

namespace EventBooking.Web.Storage;

public sealed record ImageUploadResult(ImageUploadError Error, string? BlobName = null);

/// <summary>
/// Stores event images in an Azure Blob Storage container.
/// All validation decisions come from <see cref="ImageUploadRules"/>.
/// </summary>
public sealed class ImageStorage(BlobContainerClient container, int maxImageCount)
{
    public string ContainerName => container.Name;
    public int MaxImageCount => maxImageCount;

    public async Task<ImageUploadResult> UploadAsync(IFormFile file, CancellationToken cancellationToken)
    {
        // Check the size first, before reading anything or calling Azure.
        if (file.Length > ImageUploadRules.MaxSizeBytes)
            return new(ImageUploadError.TooLarge);

        var header = new byte[ImageUploadRules.HeaderLength];
        int headerLength;
        using (var stream = file.OpenReadStream())
        {
            headerLength = await stream.ReadAtLeastAsync(
                header, header.Length, throwOnEndOfStream: false, cancellationToken);
        }

        var error = ImageUploadRules.ValidateFile(file.Length, header.AsSpan(0, headerLength), out var type);
        if (error != ImageUploadError.None)
            return new(error);

        // Only count stored blobs (a billable Azure call) once the file itself is valid.
        if (ImageUploadRules.IsStorageFull(await CountAsync(cancellationToken), maxImageCount))
            return new(ImageUploadError.StorageFull);

        // The blob name is generated by the server, never taken from the uploaded file name,
        // so users can't overwrite other blobs or inject odd paths.
        var blobName = $"{Guid.NewGuid():N}.{type!.Extension}";

        using var upload = file.OpenReadStream();
        await container.GetBlobClient(blobName).UploadAsync(upload, new BlobUploadOptions
        {
            HttpHeaders = new BlobHttpHeaders { ContentType = type.ContentType },
            // Fail instead of overwriting if a blob with this name somehow already exists.
            Conditions = new BlobRequestConditions { IfNoneMatch = ETag.All },
        }, cancellationToken);

        return new(ImageUploadError.None, blobName);
    }

    /// <summary>
    /// Counts the stored images, stopping once the limit is reached.
    /// Listing returns up to 5,000 names per call, so this is usually one request.
    /// </summary>
    public async Task<int> CountAsync(CancellationToken cancellationToken)
    {
        var count = 0;
        await foreach (var _ in container.GetBlobsAsync(cancellationToken: cancellationToken))
        {
            if (++count >= maxImageCount)
                break;
        }
        return count;
    }
}
